backend:
  name: github
  repo: esperalopy/esperalopy.github.io   # ← TU repo
  branch: main
  base_url: https://decap-oauth.netlify.app
  auth_endpoint: /api/auth

media_folder: "assets/img/productos"      # se guardan aquí las imágenes subidas
public_folder: "/assets/img/productos"    # cómo se referencian en la web

locale: "es"

publish_mode: editorial_workflow          # te permite guardar en borrador/aprobar

collections:
  - label: "Productos"
    name: "productos"
    delete: true
    editor:
      preview: false
    files:
      - label: "Catálogo"
        name: "catalogo"
        file: "assets/products.json"
        format: "json"
        fields:
          - label: "Productos"
            name: "items"                # guardará un objeto { "items": [ ... ] }
            widget: list
            summary: "{{fields.nombre}} — Gs. {{fields.precio}}"
            fields:
              - { label: "ID", name: "id", widget: "string", hint: "único, ej: prod-001" }
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text", required: false }
              - { label: "Precio (Gs.)", name: "precio", widget: "number", value_type: "int", min: 0 }
              - { label: "Moneda", name: "moneda", widget: "string", default: "PYG" }
              - { label: "Categoría", name: "categoria", widget: "select", options: ["Telefonía","Computación","Audio","Electro"] }
              - { label: "Imagen", name: "imagen", widget: "image", media_folder: "", public_folder: "" }
              - { label: "Estado (badge)", name: "estado", widget: "string", required: false, hint: "ej.: Usado • Bueno / Seminuevo / Agotado" }
              - { label: "Disponible", name: "disponible", widget: "boolean", default: true }

